# General Parameters #
SEQ_LENGTH = 100
TRAIN_SIZE = 5000
TEST_SIZE = 1000
NUM_EPOCHS = 1000
BATCH_SIZE = 128
LEARNING_RATE = 0.01
TRUNCATION_DELTA = 10
SAVE_PATH = './models/save/'
LOAD_PATH = './models/load/'
LOSS_SCALE_FACTOR = 128

# Memory Task parameters #
MEM_INPUT_SIZE = 1
MEM_HIDEN_SIZE = 32
MEM_NUM_CLASSES = 9

# Store Recall Task parameters #
SR_INPUT_SIZE = 3
SR_HIDEN_SIZE = 32
SR_NUM_CLASSES = 10